// Copyright (C) 2026 White Ravens. AGPL-3.0-only with an additional term; see LICENSE and NOTICE.

/**
 * Forge and NeoForge.
 *
 * These two are unlike Fabric and Quilt. Fabric publishes a ready-made version
 * profile as JSON over HTTP; Forge ships a **Java installer** that has to be
 * executed, because since Minecraft 1.13 the modded client is produced by
 * binary-patching and remapping the vanilla jar on the player's machine. There
 * is no static URL that returns the finished article, so there is no shortcut:
 * download the installer, run it, use what it produced.
 *
 * The installer is pointed at the launcher's own cache directory, so the
 * libraries and the patched client it writes land exactly where
 * `ensureLibraries` and the launcher already look for them. That is the whole
 * integration — no copying, no path rewriting, and nothing to keep in sync.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { log } from '../../main/logger';
import { paths } from '../config/paths';
import {
  FORGE_MAVEN_ROOT,
  FORGE_PROMOTIONS_URL,
  NEOFORGE_LEGACY_MAVEN_ROOT,
  NEOFORGE_MAVEN_ROOT,
} from '../../shared/constants';
import { getVersionMeta } from '../minecraft/version-manifest';
import type { HashAlgorithm, HashedEntry } from '../mods/integrity';
import { ensureJavaVersion, resolveChosenJava } from '../java/java-manager';
import { ensureClientJar } from '../minecraft/asset-downloader';
import { loaderCacheDir } from './loader-paths';
import { isLoaderProfileComplete, loaderProfilePath } from './loader-profile';
import { writeJsonAtomic } from '../util/atomic-file';
import { serializeByKey } from '../util/serialize';
import { readZipEntry } from '../util/zip-read';
import { downloadToFile } from '../net/download';
import { getSettings } from '../config/settings-manager';
import { CancelledError, throwIfCancelled, withTimeout } from '../util/cancellation';
import { requiredJavaFor } from '../minecraft/java-requirement';
import { compareLoaderVersionsDesc, isPrerelease } from '../../shared/loader-version';
import type { LoaderVersion, ProgressMessage } from '../../shared/ipc-types';
import type { VersionMeta } from '../minecraft/types';

const execFileAsync = promisify(execFile);

export type ForgeLikeLoader = 'forge' | 'neoforge';

/** Installing runs a Java process that downloads and patches; it is not quick. */
const INSTALLER_TIMEOUT_MS = 10 * 60 * 1000;

// ── Version listing ────────────────────────────────────────

/**
 * Pull `<version>` entries out of a Maven `maven-metadata.xml`.
 *
 * A regex rather than an XML parser on purpose: this document is machine-
 * generated by Maven, has no attributes or namespaces on the elements we want,
 * and adding a parser dependency to read one tag is not a trade worth making.
 */
function parseMavenVersions(xml: string): string[] {
  return [...xml.matchAll(/<version>([^<]+)<\/version>/g)].map((m) => m[1]);
}

async function fetchText(url: string, label: string): Promise<string> {
  const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
  if (!res.ok) throw new Error(`${label} returned ${res.status} ${res.statusText}`);
  return res.text();
}

/**
 * Forge tags every artifact with the Minecraft version it is for
 * (`1.21.4-54.1.6`, `26.2-65.1.0`), so compatibility is an exact prefix match.
 */
export function forgeVersionsFor(all: string[], mcVersion: string): string[] {
  const prefix = `${mcVersion}-`;
  return all.filter((v) => v.startsWith(prefix)).map((v) => v.slice(prefix.length));
}

/**
 * NeoForge does not name the Minecraft version — it *encodes* it.
 *
 * Under the old Minecraft scheme the leading `1.` is dropped and the rest
 * becomes the first two components, with a missing patch meaning zero:
 * 1.21.4 → 21.4.x, 1.21 → 21.0.x. Under the year-based scheme introduced with
 * Minecraft 26 the version is carried whole and padded to three components:
 * 26.2 → 26.2.0.x, 26.1.2 → 26.1.2.x.
 *
 * The trailing dot in the prefix is load-bearing: without it Minecraft 1.21.1
 * would also match every NeoForge build for 1.21.10 through 1.21.19.
 */
export function neoForgePrefix(mcVersion: string): string {
  const legacy = mcVersion.startsWith('1.');
  const parts = (legacy ? mcVersion.slice(2) : mcVersion).split('.');
  const width = legacy ? 2 : 3;
  while (parts.length < width) parts.push('0');
  return `${parts.slice(0, width).join('.')}.`;
}

export function neoForgeVersionsFor(all: string[], mcVersion: string): string[] {
  const prefix = neoForgePrefix(mcVersion);
  return all.filter((v) => v.startsWith(prefix));
}

/** NeoForge marks unfinished builds in the version string itself. */
export function isNeoForgeStable(version: string): boolean {
  return !isPrerelease(version);
}

/**
 * Forge's promotion feed, which is the only place "recommended" is published.
 *
 * A failure here is not fatal — it costs the recommendation, not the list
 * itself, so a promotions outage must not stop someone installing Forge.
 */
async function forgeRecommended(mcVersion: string): Promise<string | undefined> {
  try {
    const raw = await fetchText(FORGE_PROMOTIONS_URL, 'Forge promotions');
    const promos = (JSON.parse(raw) as { promos?: Record<string, string> }).promos ?? {};
    return promos[`${mcVersion}-recommended`];
  } catch (err) {
    log.warn(
      `Could not read Forge promotions — no build will be marked recommended: ${String(err)}`,
    );
    return undefined;
  }
}

export async function getForgeVersions(mcVersion: string): Promise<LoaderVersion[]> {
  const xml = await fetchText(`${FORGE_MAVEN_ROOT}/maven-metadata.xml`, 'Forge Maven');
  const versions = forgeVersionsFor(parseMavenVersions(xml), mcVersion);
  if (versions.length === 0) {
    log.info(`Forge has no builds for Minecraft ${mcVersion}`);
    return [];
  }

  const recommended = await forgeRecommended(mcVersion);

  // Sorted rather than reversed. Forge's metadata is in no one order: for most
  // Minecraft versions it lists the newest build first, for a few the oldest,
  // and for some a run of each. Reversing it put the *oldest* build at the head
  // of most lists — and the head is what a profile gets when Forge names no
  // recommended build or the promotions feed cannot be read. For Minecraft 1.21
  // that pinned 51.0.0 where 51.0.33 was current.
  return versions.sort(compareLoaderVersionsDesc).map((version) => ({
    version,
    // Forge publishes no prereleases under this artifact; what it does publish
    // is one promoted build per Minecraft version, which is the one to default
    // to. The rest are builds that happen to exist, not unstable ones.
    stable: true,
    recommended: version === recommended,
  }));
}

/**
 * Tell a legacy NeoForge build apart from a modern one.
 *
 * The two live under different Maven artifacts with different naming, and the
 * version string is the only thing carried between listing a version and
 * installing it. A modern build always starts with the encoded Minecraft
 * version; a legacy one (`47.1.106`) never does. That makes this total rather
 * than a guess about which Minecraft versions are "old".
 */
export function isLegacyNeoForge(loaderVersion: string, mcVersion: string): boolean {
  return !loaderVersion.startsWith(neoForgePrefix(mcVersion));
}

export async function getNeoForgeVersions(mcVersion: string): Promise<LoaderVersion[]> {
  const xml = await fetchText(`${NEOFORGE_MAVEN_ROOT}/maven-metadata.xml`, 'NeoForge Maven');
  const versions = neoForgeVersionsFor(parseMavenVersions(xml), mcVersion);

  if (versions.length > 0) {
    return versions.reverse().map((version) => ({ version, stable: isNeoForgeStable(version) }));
  }

  // Nothing under the modern artifact. Before reporting none, check the 1.20.1
  // line — NeoForge's first release, still published under the pre-rename
  // `forge` artifact with Forge-style `<mc>-<build>` versions. Only reached when
  // the modern lookup came up empty, so it costs a request on a miss and nothing
  // otherwise.
  const legacyXml = await fetchText(
    `${NEOFORGE_LEGACY_MAVEN_ROOT}/maven-metadata.xml`,
    'NeoForge (1.20.1) Maven',
  );
  const legacy = forgeVersionsFor(parseMavenVersions(legacyXml), mcVersion);
  if (legacy.length === 0) {
    log.info(`NeoForge has no builds for Minecraft ${mcVersion}`);
    return [];
  }

  log.info(`NeoForge ${mcVersion}: ${legacy.length} build(s) from the legacy artifact`);
  // That line never shipped a prerelease under this artifact.
  return legacy.reverse().map((version) => ({ version, stable: true }));
}

// ── Installation ───────────────────────────────────────────

function installerUrl(loader: ForgeLikeLoader, loaderVersion: string, mcVersion: string): string {
  if (loader === 'forge') {
    const full = `${mcVersion}-${loaderVersion}`;
    return `${FORGE_MAVEN_ROOT}/${full}/forge-${full}-installer.jar`;
  }
  if (isLegacyNeoForge(loaderVersion, mcVersion)) {
    const full = `${mcVersion}-${loaderVersion}`;
    return `${NEOFORGE_LEGACY_MAVEN_ROOT}/${full}/forge-${full}-installer.jar`;
  }
  return `${NEOFORGE_MAVEN_ROOT}/${loaderVersion}/neoforge-${loaderVersion}-installer.jar`;
}

/** The checksum sidecars a Maven repository publishes, strongest first. */
const MAVEN_CHECKSUMS: Array<{ ext: string; algorithm: HashAlgorithm }> = [
  { ext: '.sha512', algorithm: 'sha512' },
  { ext: '.sha256', algorithm: 'sha256' },
  { ext: '.sha1', algorithm: 'sha1' },
];

/**
 * The published checksum for a Maven artifact, if the repository has one.
 *
 * Maven writes these beside every artifact, so the launcher can check what it
 * is about to *execute* rather than trusting that nothing went wrong between
 * the repository and here. Returns null when the repository answers that none
 * of the sidecars exist, which is a real possibility for an old artifact and
 * not a reason to refuse the install — HTTPS is still underneath.
 *
 * Null means the repository was asked and said no. A request that got no
 * answer is thrown instead: it used to be swallowed here, so being offline read
 * as "publishes no checksum" and the player was told to switch verification
 * off.
 */
async function mavenChecksum(url: string, signal?: AbortSignal): Promise<HashedEntry | null> {
  for (const { ext, algorithm } of MAVEN_CHECKSUMS) {
    throwIfCancelled(signal, 'Loader install');
    let res: Response;
    try {
      res = await fetch(`${url}${ext}`, { signal: withTimeout(signal, 15_000) });
    } catch (err) {
      throwIfCancelled(signal, 'Loader install');
      throw new Error(`Could not reach ${new URL(url).host} to check the installer: ${err}`, {
        cause: err,
      });
    }
    if (!res.ok) continue;
    // The file is the hex digest, sometimes followed by the filename.
    const value = (await res.text()).trim().split(/\s+/)[0]?.toLowerCase();
    if (value && /^[0-9a-f]{32,128}$/.test(value)) return { [algorithm]: value };
  }
  return null;
}

/** Whether the repository has the file at all — asked only when it has no checksum for it. */
async function isPublished(url: string, signal?: AbortSignal): Promise<boolean> {
  try {
    const res = await fetch(url, { method: 'HEAD', signal: withTimeout(signal, 15_000) });
    return res.status !== 404;
  } catch {
    // No answer is not a "no": let the download itself say what is wrong.
    return true;
  }
}

async function downloadInstaller(
  url: string,
  dest: string,
  label: string,
  signal?: AbortSignal,
): Promise<void> {
  // Asked for first, so a repository serving a good checksum and a bad jar
  // cannot be answered in the other order.
  const expected = await mavenChecksum(url, signal);

  // A build that does not exist has no checksum either, and must not be
  // answered with advice about unverified installers.
  if (!expected && !(await isPublished(url, signal))) {
    throw new Error(`${label} does not publish this build: ${url} was not found`);
  }

  // Refused before a byte is fetched. This jar is executed as a Java process a
  // few lines below, which is the same argument that makes an unverifiable JRE
  // fatal in `java-manager.ts`; it used to be a `log.warn` and an install. The
  // setting exists because a genuinely old artefact may predate its
  // repository's sidecars, and that is a call for the person installing it.
  if (!expected && !(await getSettings()).allowUnverifiedLoaderInstaller) {
    throw new Error(
      `${label} publishes no checksum beside ${url}, so the installer cannot be verified — ` +
        'and it is executed. Enable "allow unverified loader installers" in Settings to ' +
        'install it anyway.',
    );
  }

  // Through the shared downloader: stall timeout, backpressure, the hash taken
  // as the bytes arrive, and no file under this name unless it matched. Executed
  // as a Java process a few lines on, so https is enforced on the way down too.
  await downloadToFile(url, dest, {
    signal,
    secure: true,
    verify: expected ? { hashes: expected, label: `${label} installer` } : undefined,
  });

  if (!expected) {
    log.warn(`${label} publishes no checksum for ${url} — the installer was not verified`);
  }
}

/**
 * The installer refuses to run without this file, and writes its own profile
 * entry into it. We never read it back — the launcher keeps its profiles
 * elsewhere — but it has to exist or the install aborts.
 */
async function ensureLauncherProfilesStub(installRoot: string): Promise<void> {
  const file = path.join(installRoot, 'launcher_profiles.json');
  try {
    await fs.access(file);
  } catch {
    await fs.mkdir(installRoot, { recursive: true });
    await fs.writeFile(file, JSON.stringify({ profiles: {}, version: 3 }, null, 2), 'utf-8');
  }
}

/**
 * The installer patches the vanilla client jar, so it has to be on disk first
 * and where the installer expects to find it.
 *
 * That place is the launcher's own `versions/` folder, so the jar is got the
 * way a launch gets it: checked against Mojang's size and hash, and fetched
 * again when it is not that file. This used to accept any file of that name —
 * and wrote straight to it — so a launcher closed mid-download left a short jar
 * that every later install went on to patch.
 */
async function ensureVanillaClientForInstaller(
  installRoot: string,
  mcVersion: string,
  meta: VersionMeta,
  signal?: AbortSignal,
): Promise<void> {
  const versionsDir = path.join(installRoot, 'versions');
  const versionDir = path.join(versionsDir, mcVersion);
  await fs.mkdir(versionDir, { recursive: true });

  // The installer reads the version JSON next to the jar to find the client
  // download; both have to be there.
  await fs.writeFile(path.join(versionDir, `${mcVersion}.json`), JSON.stringify(meta), 'utf-8');
  await ensureClientJar(versionsDir, mcVersion, meta.downloads.client, { signal });
}

/** What an install may be told beyond which build it is. */
export interface LoaderInstallOptions {
  signal?: AbortSignal;
  /** The Java the profile names, when it names one: the installer runs on it too. */
  javaPath?: string;
  /**
   * Run the installer over a build that already counts as installed.
   *
   * It is the one thing that can vouch for what it made: run again, it checks
   * every file against its own list and makes again the ones that are missing
   * or wrong, in seconds when none is. Most of those files appear in no version
   * profile, so nothing else here can so much as tell they have gone.
   */
  repair?: boolean;
}

/**
 * Install Forge or NeoForge and leave a version profile where
 * `loader-profile.ts` will find it.
 *
 * `onProgress` gets coarse phase updates rather than a percentage: the
 * installer is an opaque Java process and inventing a progress bar for it would
 * be a lie.
 */
export function installForgeLike(
  loader: ForgeLikeLoader,
  loaderVersion: string,
  mcVersion: string,
  onProgress: (fraction: number, message: ProgressMessage) => void,
  options: LoaderInstallOptions = {},
): Promise<void> {
  // One installer at a time, whichever build it is for. They all write into the
  // launcher's one cache — the same `versions/` folder, the same libraries — and
  // two profiles on one build, got ready together, used to run two of them over
  // the same files.
  return serializeByKey('forge-like-install', async () => {
    // Whoever held the turn before may have installed this very build.
    if (!options.repair && (await isLoaderProfileComplete(loader, loaderVersion, mcVersion)))
      return;
    await runInstaller(loader, loaderVersion, mcVersion, onProgress, options);
  });
}

async function runInstaller(
  loader: ForgeLikeLoader,
  loaderVersion: string,
  mcVersion: string,
  onProgress: (fraction: number, message: ProgressMessage) => void,
  { signal, javaPath }: LoaderInstallOptions,
): Promise<void> {
  const label = loader === 'forge' ? 'Forge' : 'NeoForge';
  const destDir = loaderCacheDir(loader, mcVersion, loaderVersion);
  // Installing into the launcher's own cache is what makes the libraries and
  // the patched client land where the launcher already looks for them.
  const installRoot = paths.cacheDir;

  await fs.mkdir(destDir, { recursive: true });

  onProgress(0.05, { key: 'progress.msg.installerDownloading', vars: { loader: label } });
  const installerPath = path.join(destDir, 'installer.jar');
  throwIfCancelled(signal, 'Loader install');
  await downloadInstaller(
    installerUrl(loader, loaderVersion, mcVersion),
    installerPath,
    label,
    signal,
  );

  // Read the profile out of the installer before running it: it names the
  // version id the installer is about to produce, so nothing below has to guess.
  const embedded = await readZipEntry(installerPath, 'version.json');
  if (!embedded) {
    throw new Error(
      `${label} ${loaderVersion} installer contains no version.json — it is not a client installer this launcher can use.`,
    );
  }
  const embeddedProfile = JSON.parse(embedded.toString('utf-8')) as Partial<VersionMeta>;
  const versionId = embeddedProfile.id;
  if (!versionId) throw new Error(`${label} installer's version.json has no id`);

  onProgress(0.15, { key: 'progress.msg.preparingGameFiles' });
  const vanillaMeta = await getVersionMeta(mcVersion);
  await ensureVanillaClientForInstaller(installRoot, mcVersion, vanillaMeta, signal);
  await ensureLauncherProfilesStub(installRoot);

  // The installer is a modern Java application in its own right; the JRE the
  // *game* needs is the right floor for it too — and the one the profile names
  // is the one to use, as the game will. Fetching a managed runtime regardless
  // made a profile with its own Java depend on a download it had opted out of.
  onProgress(0.25, { key: 'progress.msg.preparingJava' });
  const required = requiredJavaFor(mcVersion, vanillaMeta);
  const java = javaPath
    ? await resolveChosenJava(javaPath, required)
    : await ensureJavaVersion(required, signal);

  onProgress(0.35, { key: 'progress.msg.runningInstaller', vars: { loader: label } });
  log.info(`Running ${label} installer: ${installerPath} --installClient ${installRoot}`);

  try {
    const { stdout, stderr } = await execFileAsync(
      java.path,
      ['-jar', installerPath, '--installClient', installRoot],
      // `signal` as well as the timeout: the installer is the longest opaque
      // step in a launch, and without it a cancel sat and waited out the full
      // ten minutes. `cwd`, because the installer writes its log beside wherever
      // it was started — which was the folder the launcher happened to be run
      // from.
      {
        timeout: INSTALLER_TIMEOUT_MS,
        maxBuffer: 16 * 1024 * 1024,
        signal,
        cwd: destDir,
        windowsHide: true,
      },
    );
    log.info(`${label} installer finished.\n${stdout}`);
    if (stderr.trim()) log.warn(`${label} installer stderr:\n${stderr}`);
  } catch (err) {
    // The installer's own output is the only useful diagnostic; an exit code
    // on its own says nothing anyone can act on.
    //
    // Neither of these two is the installer failing, and both used to be
    // reported as that: a cancel came back as an error to show the player, and
    // a timeout as "installer failed" with whatever it had last printed.
    if (signal?.aborted) throw new CancelledError('Loader install');
    const detail = err as { stdout?: string; stderr?: string; message?: string; killed?: boolean };
    log.error(`${label} installer failed:\n${detail.stdout ?? ''}\n${detail.stderr ?? ''}`);
    if (detail.killed) {
      throw new Error(
        `${label} ${loaderVersion} installer was still running after ` +
          `${INSTALLER_TIMEOUT_MS / 60_000} minutes and was stopped.`,
        { cause: err },
      );
    }
    throw new Error(
      `${label} ${loaderVersion} installer failed. Last output: ${
        (detail.stderr || detail.stdout || detail.message || '')
          .trim()
          .split('\n')
          .slice(-3)
          .join(' ') || 'none'
      }`,
      { cause: err },
    );
  }

  onProgress(0.9, { key: 'progress.msg.savingProfile' });

  // Prefer what the installer actually wrote — it can differ from the embedded
  // copy — and fall back to the embedded profile only if it is missing.
  const produced = path.join(installRoot, 'versions', versionId, `${versionId}.json`);
  let profileJson: string;
  try {
    profileJson = await fs.readFile(produced, 'utf-8');
  } catch {
    log.warn(
      `${label} installer wrote no ${versionId}.json — using the copy embedded in the installer`,
    );
    profileJson = JSON.stringify(embeddedProfile, null, 2);
  }

  // Parsed on the way through, and written whole or not at all: this file is
  // what "installed" means, and the launch reads it back as the version the
  // game starts from.
  await writeJsonAtomic(
    loaderProfilePath(loader, loaderVersion, mcVersion),
    JSON.parse(profileJson) as unknown,
  );

  // The installer jar is 4–8 MB and has done its job.
  await fs.rm(installerPath, { force: true });

  onProgress(1, {
    key: 'progress.msg.loaderInstalled',
    vars: { loader: `${label} ${loaderVersion}` },
  });
  log.info(`Installed ${label} ${loaderVersion} for MC ${mcVersion} (version id ${versionId})`);
}
