/**
 * Forge and NeoForge.
 *
 * These two are unlike Fabric and Quilt. Fabric publishes a ready-made version
 * profile as JSON over HTTP; Forge ships a **Java installer** that has to be
 * executed, because since Minecraft 1.13 the modded client is produced by
 * binary-patching and remapping the vanilla jar on the player's machine. There
 * is no static URL that returns the finished article, so there is no shortcut:
 * download the installer, run it, use what it produced.
 *
 * The installer is pointed at the launcher's own cache directory, so the
 * libraries and the patched client it writes land exactly where
 * `ensureLibraries` and the launcher already look for them. That is the whole
 * integration — no copying, no path rewriting, and nothing to keep in sync.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import yauzl from 'yauzl';
import { log } from '../../main/logger';
import { paths } from '../config/paths';
import {
  FORGE_MAVEN_ROOT,
  FORGE_PROMOTIONS_URL,
  NEOFORGE_LEGACY_MAVEN_ROOT,
  NEOFORGE_MAVEN_ROOT,
} from '../../shared/constants';
import { getVersionMeta } from '../minecraft/version-manifest';
import { verifyDownload, type HashAlgorithm, type HashedEntry } from '../mods/integrity';
import { ensureJavaVersion } from '../java/java-manager';
import { loaderCacheDir } from './loader-paths';
import { downloadToFile } from '../net/download';
import { getSettings } from '../config/settings-manager';
import { throwIfCancelled, withTimeout } from '../util/cancellation';
import { requiredJavaFor } from '../minecraft/java-requirement';
import type { LoaderVersion, ProgressMessage } from '../../shared/ipc-types';
import type { VersionMeta } from '../minecraft/types';

const execFileAsync = promisify(execFile);

export type ForgeLikeLoader = 'forge' | 'neoforge';

/** Installing runs a Java process that downloads and patches; it is not quick. */
const INSTALLER_TIMEOUT_MS = 10 * 60 * 1000;

// ── Version listing ────────────────────────────────────────

/**
 * Pull `<version>` entries out of a Maven `maven-metadata.xml`.
 *
 * A regex rather than an XML parser on purpose: this document is machine-
 * generated by Maven, has no attributes or namespaces on the elements we want,
 * and adding a parser dependency to read one tag is not a trade worth making.
 */
function parseMavenVersions(xml: string): string[] {
  return [...xml.matchAll(/<version>([^<]+)<\/version>/g)].map((m) => m[1]);
}

async function fetchText(url: string, label: string): Promise<string> {
  const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
  if (!res.ok) throw new Error(`${label} returned ${res.status} ${res.statusText}`);
  return res.text();
}

/**
 * Forge tags every artifact with the Minecraft version it is for
 * (`1.21.4-54.1.6`, `26.2-65.1.0`), so compatibility is an exact prefix match.
 */
export function forgeVersionsFor(all: string[], mcVersion: string): string[] {
  const prefix = `${mcVersion}-`;
  return all.filter((v) => v.startsWith(prefix)).map((v) => v.slice(prefix.length));
}

/**
 * NeoForge does not name the Minecraft version — it *encodes* it.
 *
 * Under the old Minecraft scheme the leading `1.` is dropped and the rest
 * becomes the first two components, with a missing patch meaning zero:
 * 1.21.4 → 21.4.x, 1.21 → 21.0.x. Under the year-based scheme introduced with
 * Minecraft 26 the version is carried whole and padded to three components:
 * 26.2 → 26.2.0.x, 26.1.2 → 26.1.2.x.
 *
 * The trailing dot in the prefix is load-bearing: without it Minecraft 1.21.1
 * would also match every NeoForge build for 1.21.10 through 1.21.19.
 */
export function neoForgePrefix(mcVersion: string): string {
  const legacy = mcVersion.startsWith('1.');
  const parts = (legacy ? mcVersion.slice(2) : mcVersion).split('.');
  const width = legacy ? 2 : 3;
  while (parts.length < width) parts.push('0');
  return `${parts.slice(0, width).join('.')}.`;
}

export function neoForgeVersionsFor(all: string[], mcVersion: string): string[] {
  const prefix = neoForgePrefix(mcVersion);
  return all.filter((v) => v.startsWith(prefix));
}

/** NeoForge marks unfinished builds in the version string itself. */
export function isNeoForgeStable(version: string): boolean {
  return !/-(alpha|beta|rc)/i.test(version);
}

/**
 * Forge's promotion feed, which is the only place "recommended" is published.
 *
 * A failure here is not fatal — it costs the stable/unstable marking, not the
 * list itself, so a promotions outage must not stop someone installing Forge.
 */
async function forgePromotions(
  mcVersion: string,
): Promise<{ recommended?: string; latest?: string }> {
  try {
    const raw = await fetchText(FORGE_PROMOTIONS_URL, 'Forge promotions');
    const promos = (JSON.parse(raw) as { promos?: Record<string, string> }).promos ?? {};
    return {
      recommended: promos[`${mcVersion}-recommended`],
      latest: promos[`${mcVersion}-latest`],
    };
  } catch (err) {
    log.warn(
      `Could not read Forge promotions — versions will not be marked stable: ${String(err)}`,
    );
    return {};
  }
}

export async function getForgeVersions(mcVersion: string): Promise<LoaderVersion[]> {
  const xml = await fetchText(`${FORGE_MAVEN_ROOT}/maven-metadata.xml`, 'Forge Maven');
  const versions = forgeVersionsFor(parseMavenVersions(xml), mcVersion);
  if (versions.length === 0) {
    log.info(`Forge has no builds for Minecraft ${mcVersion}`);
    return [];
  }

  const { recommended } = await forgePromotions(mcVersion);

  // Maven metadata is oldest-first; the newest build is the useful default.
  return versions.reverse().map((version) => ({
    version,
    // "Stable" for Forge means promoted, not merely released. Everything else
    // is a build that happens to exist.
    stable: version === recommended,
  }));
}

/**
 * Tell a legacy NeoForge build apart from a modern one.
 *
 * The two live under different Maven artifacts with different naming, and the
 * version string is the only thing carried between listing a version and
 * installing it. A modern build always starts with the encoded Minecraft
 * version; a legacy one (`47.1.106`) never does. That makes this total rather
 * than a guess about which Minecraft versions are "old".
 */
export function isLegacyNeoForge(loaderVersion: string, mcVersion: string): boolean {
  return !loaderVersion.startsWith(neoForgePrefix(mcVersion));
}

export async function getNeoForgeVersions(mcVersion: string): Promise<LoaderVersion[]> {
  const xml = await fetchText(`${NEOFORGE_MAVEN_ROOT}/maven-metadata.xml`, 'NeoForge Maven');
  const versions = neoForgeVersionsFor(parseMavenVersions(xml), mcVersion);

  if (versions.length > 0) {
    return versions.reverse().map((version) => ({ version, stable: isNeoForgeStable(version) }));
  }

  // Nothing under the modern artifact. Before reporting none, check the 1.20.1
  // line — NeoForge's first release, still published under the pre-rename
  // `forge` artifact with Forge-style `<mc>-<build>` versions. Only reached when
  // the modern lookup came up empty, so it costs a request on a miss and nothing
  // otherwise.
  const legacyXml = await fetchText(
    `${NEOFORGE_LEGACY_MAVEN_ROOT}/maven-metadata.xml`,
    'NeoForge (1.20.1) Maven',
  );
  const legacy = forgeVersionsFor(parseMavenVersions(legacyXml), mcVersion);
  if (legacy.length === 0) {
    log.info(`NeoForge has no builds for Minecraft ${mcVersion}`);
    return [];
  }

  log.info(`NeoForge ${mcVersion}: ${legacy.length} build(s) from the legacy artifact`);
  // That line never shipped a prerelease under this artifact.
  return legacy.reverse().map((version) => ({ version, stable: true }));
}

// ── Installation ───────────────────────────────────────────

function installerUrl(loader: ForgeLikeLoader, loaderVersion: string, mcVersion: string): string {
  if (loader === 'forge') {
    const full = `${mcVersion}-${loaderVersion}`;
    return `${FORGE_MAVEN_ROOT}/${full}/forge-${full}-installer.jar`;
  }
  if (isLegacyNeoForge(loaderVersion, mcVersion)) {
    const full = `${mcVersion}-${loaderVersion}`;
    return `${NEOFORGE_LEGACY_MAVEN_ROOT}/${full}/forge-${full}-installer.jar`;
  }
  return `${NEOFORGE_MAVEN_ROOT}/${loaderVersion}/neoforge-${loaderVersion}-installer.jar`;
}

function loaderInstallDir(
  loader: ForgeLikeLoader,
  loaderVersion: string,
  mcVersion: string,
): string {
  return loaderCacheDir(loader, mcVersion, loaderVersion);
}

/** Read one entry out of a zip into memory. Returns null when it is not there. */
function readZipEntry(jarPath: string, wanted: string): Promise<Buffer | null> {
  return new Promise((resolve, reject) => {
    yauzl.open(jarPath, { lazyEntries: true }, (openErr, zip) => {
      if (openErr || !zip) {
        reject(openErr ?? new Error(`Could not open ${jarPath}`));
        return;
      }
      let found = false;
      zip.on('entry', (entry: yauzl.Entry) => {
        if (entry.fileName !== wanted) {
          zip.readEntry();
          return;
        }
        found = true;
        zip.openReadStream(entry, (err, stream) => {
          if (err || !stream) {
            reject(err ?? new Error(`Could not read ${wanted} from ${jarPath}`));
            return;
          }
          const chunks: Buffer[] = [];
          stream.on('data', (c: Buffer) => chunks.push(c));
          stream.on('end', () => resolve(Buffer.concat(chunks)));
          stream.on('error', reject);
        });
      });
      zip.on('end', () => {
        if (!found) resolve(null);
      });
      zip.on('error', reject);
      zip.readEntry();
    });
  });
}

/** The checksum sidecars a Maven repository publishes, strongest first. */
const MAVEN_CHECKSUMS: Array<{ ext: string; algorithm: HashAlgorithm }> = [
  { ext: '.sha512', algorithm: 'sha512' },
  { ext: '.sha256', algorithm: 'sha256' },
  { ext: '.sha1', algorithm: 'sha1' },
];

/**
 * The published checksum for a Maven artifact, if the repository has one.
 *
 * Maven writes these beside every artifact, so the launcher can check what it
 * is about to *execute* rather than trusting that nothing went wrong between
 * the repository and here. Returns null when none of the sidecars exist, which
 * is a real possibility for an old artifact and not a reason to refuse the
 * install — HTTPS is still underneath.
 */
async function mavenChecksum(url: string, signal?: AbortSignal): Promise<HashedEntry | null> {
  for (const { ext, algorithm } of MAVEN_CHECKSUMS) {
    try {
      const res = await fetch(`${url}${ext}`, { signal: withTimeout(signal, 15_000) });
      if (!res.ok) continue;
      // The file is the hex digest, sometimes followed by the filename.
      const value = (await res.text()).trim().split(/\s+/)[0]?.toLowerCase();
      if (value && /^[0-9a-f]{32,128}$/.test(value)) return { [algorithm]: value };
    } catch {
      /* sidecar unreachable — try the next, then go without */
    }
  }
  return null;
}

async function downloadInstaller(
  url: string,
  dest: string,
  label: string,
  signal?: AbortSignal,
): Promise<void> {
  // Asked for first, so a repository serving a good checksum and a bad jar
  // cannot be answered in the other order.
  const expected = await mavenChecksum(url, signal);

  // Refused before a byte is fetched. This jar is executed as a Java process a
  // few lines below, which is the same argument that makes an unverifiable JRE
  // fatal in `java-manager.ts`; it used to be a `log.warn` and an install. The
  // setting exists because a genuinely old artefact may predate its
  // repository's sidecars, and that is a call for the person installing it.
  if (!expected && !(await getSettings()).allowUnverifiedLoaderInstaller) {
    throw new Error(
      `${label} publishes no checksum beside ${url}, so the installer cannot be verified — ` +
        'and it is executed. Enable "allow unverified loader installers" in Settings to ' +
        'install it anyway.',
    );
  }

  // Through the shared downloader: stall timeout, backpressure, and the file
  // removed on any failure. This used to be `res.arrayBuffer()`, which held the
  // whole installer in memory and left a partial file behind when it failed.
  // Executed as a Java process a few lines on, so https is enforced on the way
  // down as well as the checksum once it lands.
  await downloadToFile(url, dest, { signal, secure: true });

  if (expected) {
    // Deletes the file and throws on mismatch — this jar is about to be run.
    await verifyDownload(dest, expected, `${label} installer`);
  } else {
    log.warn(`${label} publishes no checksum for ${url} — the installer was not verified`);
  }
}

/**
 * The installer refuses to run without this file, and writes its own profile
 * entry into it. We never read it back — the launcher keeps its profiles
 * elsewhere — but it has to exist or the install aborts.
 */
async function ensureLauncherProfilesStub(installRoot: string): Promise<void> {
  const file = path.join(installRoot, 'launcher_profiles.json');
  try {
    await fs.access(file);
  } catch {
    await fs.mkdir(installRoot, { recursive: true });
    await fs.writeFile(file, JSON.stringify({ profiles: {}, version: 3 }, null, 2), 'utf-8');
  }
}

/**
 * The installer patches the vanilla client jar, so it has to be on disk first
 * and where the installer expects to find it.
 */
async function ensureVanillaClientForInstaller(
  installRoot: string,
  mcVersion: string,
  meta: VersionMeta,
  signal?: AbortSignal,
): Promise<void> {
  const versionDir = path.join(installRoot, 'versions', mcVersion);
  await fs.mkdir(versionDir, { recursive: true });

  // The installer reads the version JSON next to the jar to find the client
  // download; both have to be there.
  await fs.writeFile(path.join(versionDir, `${mcVersion}.json`), JSON.stringify(meta), 'utf-8');

  const jarPath = path.join(versionDir, `${mcVersion}.jar`);
  try {
    await fs.access(jarPath);
    return;
  } catch {
    /* not there yet */
  }

  log.info(`Downloading vanilla client jar ${mcVersion} for the installer...`);
  // Streamed, not `arrayBuffer()`: this jar is around 26 MB and used to be
  // fully resident in memory on its way to disk — the same waste `integrity.ts`
  // removed from hashing and did not remove from here.
  // Mojang serves this over https and its sha1 is checked just below; the flag
  // refuses a redirect that would drop the jar the installer patches to http.
  await downloadToFile(meta.downloads.client.url, jarPath, { signal, secure: true });

  // Mojang's own sha1 is already in hand, and the normal launch path checks the
  // very same file against it. This copy is the one a Java installer is about
  // to patch and the game is then going to run, so there is no argument for
  // being the one place that skips the check.
  await verifyDownload(jarPath, { sha1: meta.downloads.client.sha1 }, `client jar ${mcVersion}`);
}

/**
 * Install Forge or NeoForge and leave a version profile where
 * `loader-profile.ts` will find it.
 *
 * `onProgress` gets coarse phase updates rather than a percentage: the
 * installer is an opaque Java process and inventing a progress bar for it would
 * be a lie.
 */
export async function installForgeLike(
  loader: ForgeLikeLoader,
  loaderVersion: string,
  mcVersion: string,
  onProgress: (fraction: number, message: ProgressMessage) => void,
  signal?: AbortSignal,
): Promise<void> {
  const label = loader === 'forge' ? 'Forge' : 'NeoForge';
  const destDir = loaderInstallDir(loader, loaderVersion, mcVersion);
  // Installing into the launcher's own cache is what makes the libraries and
  // the patched client land where the launcher already looks for them.
  const installRoot = paths.cacheDir;

  await fs.mkdir(destDir, { recursive: true });

  onProgress(0.05, { key: 'progress.msg.installerDownloading', vars: { loader: label } });
  const installerPath = path.join(destDir, 'installer.jar');
  throwIfCancelled(signal, 'Loader install');
  await downloadInstaller(
    installerUrl(loader, loaderVersion, mcVersion),
    installerPath,
    label,
    signal,
  );

  // Read the profile out of the installer before running it: it names the
  // version id the installer is about to produce, so nothing below has to guess.
  const embedded = await readZipEntry(installerPath, 'version.json');
  if (!embedded) {
    throw new Error(
      `${label} ${loaderVersion} installer contains no version.json — it is not a client installer this launcher can use.`,
    );
  }
  const embeddedProfile = JSON.parse(embedded.toString('utf-8')) as Partial<VersionMeta>;
  const versionId = embeddedProfile.id;
  if (!versionId) throw new Error(`${label} installer's version.json has no id`);

  onProgress(0.15, { key: 'progress.msg.preparingGameFiles' });
  const vanillaMeta = await getVersionMeta(mcVersion);
  await ensureVanillaClientForInstaller(installRoot, mcVersion, vanillaMeta, signal);
  await ensureLauncherProfilesStub(installRoot);

  // The installer is a modern Java application in its own right; the JRE the
  // *game* needs is the right floor for it too.
  onProgress(0.25, { key: 'progress.msg.preparingJava' });
  const java = await ensureJavaVersion(requiredJavaFor(mcVersion, vanillaMeta), signal);

  onProgress(0.35, { key: 'progress.msg.runningInstaller', vars: { loader: label } });
  log.info(`Running ${label} installer: ${installerPath} --installClient ${installRoot}`);

  try {
    const { stdout, stderr } = await execFileAsync(
      java.path,
      ['-jar', installerPath, '--installClient', installRoot],
      // `signal` as well as the timeout: the installer is the longest opaque
      // step in a launch, and without it a cancel sat and waited out the full
      // ten minutes.
      { timeout: INSTALLER_TIMEOUT_MS, maxBuffer: 16 * 1024 * 1024, signal },
    );
    log.info(`${label} installer finished.\n${stdout}`);
    if (stderr.trim()) log.warn(`${label} installer stderr:\n${stderr}`);
  } catch (err) {
    // The installer's own output is the only useful diagnostic; an exit code
    // on its own says nothing anyone can act on.
    const detail = err as { stdout?: string; stderr?: string; message?: string };
    log.error(`${label} installer failed:\n${detail.stdout ?? ''}\n${detail.stderr ?? ''}`);
    throw new Error(
      `${label} ${loaderVersion} installer failed. Last output: ${
        (detail.stderr || detail.stdout || detail.message || '')
          .trim()
          .split('\n')
          .slice(-3)
          .join(' ') || 'none'
      }`,
      { cause: err },
    );
  }

  onProgress(0.9, { key: 'progress.msg.savingProfile' });

  // Prefer what the installer actually wrote — it can differ from the embedded
  // copy — and fall back to the embedded profile only if it is missing.
  const produced = path.join(installRoot, 'versions', versionId, `${versionId}.json`);
  let profileJson: string;
  try {
    profileJson = await fs.readFile(produced, 'utf-8');
  } catch {
    log.warn(
      `${label} installer wrote no ${versionId}.json — using the copy embedded in the installer`,
    );
    profileJson = JSON.stringify(embeddedProfile, null, 2);
  }

  await fs.writeFile(path.join(destDir, `${loader}-profile.json`), profileJson, 'utf-8');

  // The installer jar is 4–8 MB and has done its job.
  await fs.rm(installerPath, { force: true });

  onProgress(1, {
    key: 'progress.msg.loaderInstalled',
    vars: { loader: `${label} ${loaderVersion}` },
  });
  log.info(`Installed ${label} ${loaderVersion} for MC ${mcVersion} (version id ${versionId})`);
}

export async function isForgeLikeInstalled(
  loader: ForgeLikeLoader,
  loaderVersion: string,
  mcVersion: string,
): Promise<boolean> {
  const profilePath = path.join(
    loaderInstallDir(loader, loaderVersion, mcVersion),
    `${loader}-profile.json`,
  );
  return fs
    .access(profilePath)
    .then(() => true)
    .catch(() => false);
}
